services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      volumes:
        - db:/data/postgres
      ports:
        - "5332:5432"
      networks:
        - db
      restart: unless-stopped

      network:
        db:
          driver: bridge

      volume:
        db:

